version: '3.9'

services:

  phpmyadmin:
    image: phpmyadmin
    container_name: ${PROJECT_NAME}
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOSTS: ${FIRST_SERVER_CONTAINER_NAME}
      PMA_PORTS: ${MYSQL_PORT}

networks:
  default:
    name: ${NETWORK_NAME}
